---
title: "Untitled"
author: "Michael Stölzle"
date: "9/25/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(delayedflow)
options(dplyr.summarise.inform=F)
```


```{r}
df <- read_tsv('https://raw.githubusercontent.com/modche/science_contr/master/4ezg.txt', col_types = cols())
```

```{r}


df %>% 
	group_by(filename) %>% 
	summarise(cdc = dfi_n(q = q, n = 1:180)$dfi, .groups = "keep", n = 0:180 ) %>% 
	ungroup() %>% 
	ggplot(aes(x=n, y = cdc)) +
		geom_line(aes(colour = filename))

df2 <- df %>% 
	group_by(filename) %>% 
	summarise(cdc = dfi_n(q = q, n = 1:180)$dfi, .groups = "keep", n = 0:180 ) %>% 
	ungroup()


bp_df <- df2 %>% 
		group_by(filename) %>% 
		summarize(bps = find_bps(cdc, n_bp = 3, bp_max = 65)$bps_position) %>% 
		mutate(id = names(bps)) %>% 
		ungroup() %>% 
		pivot_wider(names_from = "id", values_from = "bps")


exa1 <- df %>% filter(filename == "catchment4") %>% 
	
	mutate(interflow = baseflow(q, block.len = as.numeric(bp_df[1,2]))) %>% 
	mutate(interflow = baseflow(q, block.len = as.numeric(bp_df[1,2]))) %>% 
	mutate(baseflow = baseflow(q, block.len = as.numeric(bp_df[1,3])))

ggplot(data = filter(exa1, date > "2000-01-01")) +
	geom_ribbon(aes(x = date, ymax = q, ymin = 0.05), fill = "red") +
	geom_ribbon(aes(x = date, ymax = interflow, ymin = 0.05), fill = "lightblue") +
	geom_ribbon(aes(x = date, ymax = baseflow, ymin = 0.05), fill = "blue") +
	theme_bw(15) + scale_y_log10()
```

